FROM node:20-alpine

WORKDIR /app

COPY package.json ./
COPY apps/web/package.json ./apps/web/
COPY packages/sdk/package.json ./packages/sdk/

RUN npm install

COPY . .

WORKDIR /app/apps/web

CMD ["npm", "run", "dev"]